apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: softcon-ingress
  namespace: default
spec:
  rules:
    - host: softcon.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: softcon-nodeport-service
                port:
                  number: 8081 
  tls:
    - hosts:
        - softcon.com
      secretName: my-tls-secret 







