apiVersion: v1
kind: Service
metadata:
  name: softcon-loadbalance-service
spec:
  selector:
    app: softcon
  ports:
    - port: 8081
      targetPort: 5000
      name: https
  clusterIP: 10.152.183.3
  type: LoadBalancer