"""empty message

Revision ID: dd069b6e8c63
Revises: d9f2cc275dea
Create Date: 2022-01-23 23:47:39.706210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd069b6e8c63'
down_revision = 'd9f2cc275dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_categories', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_column('blog_categories', 'featured_photo')
    op.drop_column('blog_categories', 'is_featured')
    op.drop_column('blog_categories', 'tags')
    op.add_column('blog_reads', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('blogs', sa.Column('publisher', sa.String(), nullable=False))
    op.add_column('blogs', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_constraint('blogs_publisher_user_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'is_deleted')
    op.drop_column('blogs', 'publisher_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('publisher_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_publisher_user_id_fkey', 'blogs', 'users', ['publisher_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('blogs', 'modified_at')
    op.drop_column('blogs', 'publisher')
    op.drop_column('blog_reads', 'modified_at')
    op.add_column('blog_categories', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blog_categories', sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('blog_categories', sa.Column('featured_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blog_categories', 'modified_at')
    # ### end Alembic commands ###
